## **TRABAJO PRÁCTICO 02: Procesos ETL** 

**Alumno: Huici Nicolas**
**Legajo: 165755**

# **Consignas** 

A partir del dataset Education Data<sup>3</sup> del World Bank Group, desarrollar los flujos necesarios para generar los siguientes archivos de salida (en formato CSV):

## 1. **CSV de Países con la siguiente estructura:** 

- Campos requeridos: 

   - id: Identificador numérico entero autoincremental (1, 2, 3, ...). 

   - nombre_pais: Nombre oficial del país o entidad regional. 

   - codigo_pais: Código estándar de 3 letras (ISO Alpha-3). 

- Transformaciones esperadas: 

   - Limpieza de registros nulos o datos faltantes en los campos base. 

   - Eliminación de duplicados.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("API_4_DS2_en_csv_v2_3434744.csv", encoding="utf-8-sig")
print(df.shape)
display(df.head())
df.info()

(43624, 69)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,Population ages 15-64 (% of total population),SP.POP.1564.TO.ZS,54.495678,54.588701,54.585630,54.674206,54.873448,55.181477,...,69.352325,69.027743,68.681269,68.320569,67.962515,67.712003,67.657094,67.617079,67.432276,NaN
1,Aruba,ABW,Population ages 0-14 (% of total population),SP.POP.0014.TO.ZS,43.131043,42.949419,42.852732,42.661157,42.359159,41.936664,...,18.799607,18.571721,18.334859,18.069771,17.767339,17.351022,16.799407,16.240782,15.711772,NaN
2,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aruba,ABW,"Unemployment, male (% of male labor force) (mo...",SL.UEM.TOTL.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aruba,ABW,"Unemployment, female (% of female labor force)...",SL.UEM.TOTL.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 43624 entries, 0 to 43623
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    43624 non-null  str
 1   Country Code    43624 non-null  str
 2   Indicator Name  43624 non-null  str
 3   Indicator Code  43624 non-null  str
 4   1960            530 non-null    float64
 5   1961            530 non-null    float64
 6   1962            530 non-null    float64
 7   1963            530 non-null    float64
 8   1964            530 non-null    float64
 9   1965            530 non-null    float64
 10  1966            530 non-null    float64
 11  1967            530 non-null    float64
 12  1968            530 non-null    float64
 13  1969            530 non-null    float64
 14  1970            5305 non-null   float64
 15  1971            9327 non-null   float64
 16  1972            9341 non-null   float64
 17  1973            9277 non-null   float64
 18  1974            9282 non-null   float64
 19  1975            9381 non-null   float64
 20  1976            9848 non-null   float64
 21  1977            9727 non-null   float64
 22  1978            9792 non-null   float64
 23  1979            9817 non-null   float64
 24  1980            10075 non-null  float64
 25  1981            10557 non-null  float64
 26  1982            10156 non-null  float64
 27  1983            10385 non-null  float64
 28  1984            10497 non-null  float64
 29  1985            10372 non-null  float64
 30  1986            10754 non-null  float64
 31  1987            10318 non-null  float64
 32  1988            10285 non-null  float64
 33  1989            10259 non-null  float64
 34  1990            12302 non-null  float64
 35  1991            13968 non-null  float64
 36  1992            13866 non-null  float64
 37  1993            13849 non-null  float64
 38  1994            14214 non-null  float64
 39  1995            13939 non-null  float64
 40  1996            13740 non-null  float64
 41  1997            12743 non-null  float64
 42  1998            14418 non-null  float64
 43  1999            18905 non-null  float64
 44  2000            19722 non-null  float64
 45  2001            19737 non-null  float64
 46  2002            19915 non-null  float64
 47  2003            19489 non-null  float64
 48  2004            20437 non-null  float64
 49  2005            20891 non-null  float64
 50  2006            21163 non-null  float64
 51  2007            21729 non-null  float64
 52  2008            22164 non-null  float64
 53  2009            22396 non-null  float64
 54  2010            22923 non-null  float64
 55  2011            23614 non-null  float64
 56  2012            23595 non-null  float64
 57  2013            23411 non-null  float64
 58  2014            24246 non-null  float64
 59  2015            24384 non-null  float64
 60  2016            24331 non-null  float64
 61  2017            23772 non-null  float64
 62  2018            21727 non-null  float64
 63  2019            18526 non-null  float64
 64  2020            17498 non-null  float64
 65  2021            16354 non-null  float64
 66  2022            13193 non-null  float64
 67  2023            3853 non-null   float64
 68  Unnamed: 68     0 non-null      float64
dtypes: float64(65), str(4)
memory usage: 26.8 MB

In [3]:
df_paises = (
    df[["Country Name", "Country Code"]]
    .rename(columns={"Country Name": "nombre_pais", "Country Code": "codigo_pais"})
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

df_paises.insert(0, "id", range(1, len(df_paises) + 1))

display(df_paises.head(10))
df_paises.info()

   id                  nombre_pais codigo_pais
0   1                        Aruba         ABW
1   2  Africa Eastern and Southern         AFE
2   3                  Afghanistan         AFG
3   4   Africa Western and Central         AFW
4   5                       Angola         AGO
5   6                      Albania         ALB
6   7                      Andorra         AND
7   8                   Arab World         ARB
8   9         United Arab Emirates         ARE
9  10                    Argentina         ARG

<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           266 non-null    int64
 1   nombre_pais  266 non-null    str
 2   codigo_pais  266 non-null    str
dtypes: int64(1), str(2)
memory usage: 10.4 KB

In [4]:
df_paises.to_csv("data_ETL/paises.csv", index=False)

## **2. CSV de Preguntas con la siguiente estructura:** 

   - Campos requeridos: 

      - id: Identificador numérico entero autoincremental. 

      - pregunta: Descripción corta del indicador o pregunta educativa. 

   - Transformaciones esperadas: 

      - Tratamiento de texto: Expresión regular (RegEx) o manipulación de cadenas para remover completamente cualquier contenido que se encuentre entre paréntesis (incluyendo los propios paréntesis) y aplicar un trim para eliminar espacios extra resultantes. 

      - Consolidar indicadores únicos sin duplicados.

In [5]:
df_preguntas = (
    df[["Indicator Name"]]
    .rename(columns={"Indicator Name": "pregunta",})
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

df_preguntas["pregunta"] = (df_preguntas["pregunta"].str.replace(
    r"\s*\([^)]*\)",
    "",
    regex=True
).str.strip())

df_preguntas = df_preguntas.drop_duplicates().reset_index(drop=True)
df_preguntas = df_preguntas.dropna()

df_preguntas.insert(0, "id", range(1, len(df_preguntas) + 1))

display(df_preguntas.head(20))

    id                                           pregunta
0    1                              Population ages 15-64
1    2                               Population ages 0-14
2    3                                Unemployment, total
3    4                                 Unemployment, male
4    5                               Unemployment, female
5    6                                 Labor force, total
6    7                                Labor force, female
7    8  Probability of dying among youth ages 20-24 years
8    9  Probability of dying among adolescents ages 15...
9   10  Probability of dying among adolescents ages 10...
10  11  Probability of dying among children ages 5-9 y...
11  12                  Number of deaths ages 20-24 years
12  13                  Number of deaths ages 15-19 years
13  14                  Number of deaths ages 10-14 years
14  15                    Number of deaths ages 5-9 years
15  16         Government expenditure on education, total
16  17                  Expenditure on tertiary education
17  18       Government expenditure per student, tertiary
18  19                 Expenditure on secondary education
19  20      Government expenditure per student, secondary

In [6]:
df_preguntas.to_csv("data_ETL/preguntas.csv", index=False)

## **3. CSV de Educación primaria en años ordenado por duración de mayor a menor según el año 2023** 

   - Campos requeridos: 

      - País / Código de País. 

      - Duración de la educación primaria en años. 

   - Transformaciones esperadas: 

      - Filtrar exclusivamente el indicador correspondiente a la duración de la educación primaria en años. 

      - Filtrar o considerar únicamente la medición correspondiente al año 2023. 

      - Tratar valores nulos o no reportados para dicho año (especificar en el informe la estrategia adoptada: imputación, descarte, etc.). 

      - Ordenamiento: Ordenar los datos de mayor a menor según la duración en años.

In [28]:
df_primaria_total = df[df.iloc[:, 3] == "SE.PRM.DURS"]

df_primaria_2023 = (
    df_primaria_total[["Country Name", "Country Code", "2023"]]
    .rename(columns={"Country Name": "nombre_pais", "Country Code": "codigo_pais", "2023": "dur_prm_anios_2023"})
    .dropna()
    .reset_index(drop=True)
)
df_primaria_2023["dur_prm_anios_2023"] = df_primaria_2023["dur_prm_anios_2023"].astype(int)

df_primaria_2023 = df_primaria_2023.sort_values(["dur_prm_anios_2023", "codigo_pais"], ascending=[False, True]).reset_index(drop=True)

df_primaria_2023.info()
df_primaria_2023.head()

<class 'pandas.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nombre_pais         255 non-null    str
 1   codigo_pais         255 non-null    str
 2   dur_prm_anios_2023  255 non-null    int64
dtypes: int64(1), str(2)
memory usage: 10.0 KB

           nombre_pais codigo_pais  dur_prm_anios_2023
0                 Guam         GUM                   8
1              Ireland         IRL                   8
2  Antigua and Barbuda         ATG                   7
3            Australia         AUS                   7
4               Bhutan         BTN                   7

In [29]:
df_primaria_2023.to_csv("data_ETL/primaria_2023.csv", index=False)